export const NON_TEXT_INPUT_TYPES = new Set([
  "hidden",
  "checkbox",
  "radio",
  "submit",
  "button",
  "file",
  "image",
  "range",
  "color",
  "reset",
]);

export const SENSITIVE_FIELD_PATTERNS = [
  /card number/i,
  /credit card/i,
  /debit card/i,
  /\bcard\b/i,
  /\bcvv\b/i,
  /\bcvc\b/i,
  /security code/i,
  /expiry/i,
  /expiration/i,
  /exp date/i,
  /mm\/yy/i,
  /mm-yyyy/i,
  /iban/i,
  /swift/i,
  /date of birth/i,
  /\bdob\b/i,
  /birthday/i,
  /\bssn\b/i,
  /social security/i,
  /\bpassword\b/i,
  /\bpasscode\b/i,
  /\bpin\b/i,
  /licen[cs]e number/i,
  /driver'?s licen[cs]e/i,
  /passport (number|no)/i,
  /medicare (number|no)/i,
  /tax file number/i,
  /\btfn\b/i,
];
